### ISSUE TITLE
typo in index.html

### ISSUE THREAD

**Issue by torchhound** [nalck/ixtech.net#1]
This might have to do with the formatting, text editor used in creation, or the fact that on GitHub the sentence is on a new line. In any case this sentence has a typo in Firefox and Safari: "Ix Technology is committed to Open Source development
		and collegiality." 

In browser it reads "developmentand" and should have a space.

**Comment by nalck** [comment]
Thanks for taking the time to review my work.

I'm running Firefox (v. 39.0.3), and can't reproduce this bug. Chrome, Epiphany, and w3m don't have the typo. What version are you using? Did you look at the experimental live site in Yesod or run the raw HTML from my repo? 

I know that in HTML newlines within paragraphs are designed to display as spaces by the [W3C](http://www.w3.org/TR/REC-html40/struct/text.html#h-9.1).

**Comment by torchhound** [comment]
I was unaware that there were multiple versions and apologize if I am reporting this issue in the wrong place. I encountered this issue on gavwhela.mooo.com.

**Comment by nalck** [comment]
No apologies necessary. [@gavwhela](https://github.com/gavwhela) has been porting my work over to the [Yesod](http://www.yesodweb.com/) framework. I've not enough Haskell to really dig in, but it seems that porting sometimes introduces bugs unrelated to the original source code.

I'll mark this as resolved, and thank you again for taking time to review the site.
